#!/bin/sh

echo "Content-type: text/html"
echo ""

cat << EOF
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Xiaomi Xiaofang IP Camera - Messages log</title>
EOF

/tmp/www/cgi-bin/parts/head

cat << EOF
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index.html">Xiaomi Xiaofang</a>
            </div>
            <!-- /.navbar-header -->
           
EOF
/tmp/www/cgi-bin/parts/side-menu
cat << EOF
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Messages log</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div  class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Timestamp</th>
                                        <th>Device</th>
										<th>Process</th>
										<th>Message</th>
                                    </tr>
                                </thead>
                                <tbody>                                    
EOF
cat /var/log/messages | while read month day time device process message; do
   echo "   <tr>
      <td>${month} ${day} ${time}</td><td>${device}</td><td>${process}</td><td>${message}</td>
   </tr>"
done

cat << EOF

								</tbody>
							</table>
                        </div>                        
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>
EOF
